spring:
  application:
    name: konvergion-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/personalfinance-konvergion/KONVERGION-CLOUD-CONFIG-STORE
          username: discovered1086
          password: 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

server:
  port: 8100
