server:
  port: 8010

spring:
    application:
      name: microservice-course-config-server
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: 123456
    cloud:
      config:
        server:
          git:
            uri: https://github.com/discovered1086/SPRING-MICROSERVICE-CLOUD-PROJECTS-CONFIG
