package com.konvergion.personalfinance.budgetmanagementapi.model.repository;

import com.konvergion.personalfinance.budgetmanagementapi.model.entities.CalculationBudgetEstimateItemEntity;
import com.konvergion.personalfinance.budgetmanagementapi.model.entities.RegularBudgetEstimateItemEntity;

public interface CalculatedBudgetEstimateItemRepository extends BudgetEstimateItemRepository<CalculationBudgetEstimateItemEntity> {
}