INSERT INTO EXCHANGE_VALUES(ID, FROM_CURRENCY, TO_CURRENCY, EXCHANGE_RATE) VALUES(1000, 'USD', 'INR', 72.00);
INSERT INTO EXCHANGE_VALUES(ID, FROM_CURRENCY, TO_CURRENCY, EXCHANGE_RATE) VALUES(1001, 'EUR', 'INR', 75.00);
INSERT INTO EXCHANGE_VALUES(ID, FROM_CURRENCY, TO_CURRENCY, EXCHANGE_RATE) VALUES(1002, 'AUD', 'INR', 55.00);